#! /bin/bash

export CGO_ENABLED=0

echo running staticcheck...
hash staticcheck >/dev/null && staticcheck ./...

echo running tests...
go test ./...

echo building and installing...
go install ./samples/...
